name: Build LaTeX documents

on:
  pull_request:
    branches:
      - trunk

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dotted.tex
          latexmk_use_xelatex: true
          post_compile: pdfjam --vanilla --noautoscale true --angle 90 --nup 2x1 --suffix '2x1' --booklet true  dotted.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: Dotted
          path: dotted-2x1.pdf
