name: Build PDF documents
on:
  workflow_call:
  pull_request:
    branches:
      - trunk
  push:
    tags:
      - v*

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - dotted
          - gridded
          - sota-log

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Update git info
        run: ./update-git-info.sh

      - name: Compile inlay
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.name }}-inlay.tex
          latexmk_use_xelatex: true

      - name: Compile main document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.name }}.tex
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.name }}.pdf

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build_pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact/*"
          body: ${{ steps.build_changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
