name: Build LaTeX documents

on:
  pull_request:
    branches:
      - trunk

jobs:
  build_latex:
    strategy:
      matrix:
        name:
          - dotted
          - gridded
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.name }}.tex
          latexmk_use_xelatex: true
          post_compile: pdfjam --vanilla --noautoscale true --angle 90 --nup 2x1 --suffix 'booklet' --booklet true ${{ matrix.name }}.pdf
      - name: Append licence
        uses: xu-cheng/latex-action@v2
        with:
          root_file: license.tex
          latexmk_use_xelatex: true
          post_compile: pdfjam --vanilla --noautoscale true --outfile ${{ matrix.name }}.pdf ${{ matrix.name }}-booklet.pdf license.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.pdf
